-- Baseline schema for the public schema of project gphxemepikbgwcnxewks.
-- Generated by introspecting the live database. Captures tables, columns,
-- constraints, indexes, RLS policies, functions, triggers and views so the
-- whole game logic is reproducible from migrations.

-- Extensions (uuid_generate_v4 lives in the extensions schema on Supabase)
create extension if not exists "uuid-ossp" with schema extensions;

-- Enum types
create type public.league_type as enum ('private', 'company');
create type public.league_member_role as enum ('admin', 'member');
create type public.match_status as enum ('upcoming', 'live', 'finished', 'postponed', 'cancelled');
create type public.prediction_lock_status as enum ('open', 'locked');

create table public.audit_logs (
  id uuid default extensions.uuid_generate_v4() not null,
  actor_id uuid,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  old_value jsonb,
  new_value jsonb,
  created_at timestamp with time zone default now() not null
);

create table public.companies (
  id uuid default extensions.uuid_generate_v4() not null,
  name text not null,
  owner_id uuid not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.company_members (
  id uuid default extensions.uuid_generate_v4() not null,
  company_id uuid not null,
  user_id uuid not null,
  role text default 'member'::text not null,
  created_at timestamp with time zone default now() not null
);

create table public.invitations (
  id uuid default extensions.uuid_generate_v4() not null,
  league_id uuid not null,
  invite_code text not null,
  created_by uuid not null,
  expires_at timestamp with time zone,
  max_uses integer,
  used_count integer default 0 not null,
  created_at timestamp with time zone default now() not null
);

create table public.league_members (
  id uuid default extensions.uuid_generate_v4() not null,
  league_id uuid not null,
  user_id uuid not null,
  role league_member_role default 'member'::league_member_role not null,
  joined_at timestamp with time zone default now() not null
);

create table public.leagues (
  id uuid default extensions.uuid_generate_v4() not null,
  name text not null,
  type league_type default 'private'::league_type not null,
  company_id uuid,
  owner_id uuid not null,
  invite_code text not null,
  is_private boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  tournament_id uuid
);

create table public.matches (
  id uuid default extensions.uuid_generate_v4() not null,
  tournament_id uuid not null,
  external_id text,
  round text,
  group_name text,
  home_team_id uuid,
  away_team_id uuid,
  kickoff_at timestamp with time zone not null,
  status match_status default 'upcoming'::match_status not null,
  home_goals integer,
  away_goals integer,
  result_source text,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.points (
  id uuid default extensions.uuid_generate_v4() not null,
  league_id uuid not null,
  user_id uuid not null,
  match_id uuid not null,
  prediction_id uuid not null,
  home_goal_points integer default 0 not null,
  away_goal_points integer default 0 not null,
  sign_points integer default 0 not null,
  total_points integer default 0 not null,
  calculated_at timestamp with time zone default now() not null
);

create table public.predictions (
  id uuid default extensions.uuid_generate_v4() not null,
  league_id uuid not null,
  user_id uuid not null,
  match_id uuid not null,
  predicted_home_goals integer not null,
  predicted_away_goals integer not null,
  lock_status prediction_lock_status default 'open'::prediction_lock_status not null,
  submitted_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  predicted_winner_team text
);

create table public.profiles (
  id uuid not null,
  full_name text not null,
  email text,
  avatar_url text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.teams (
  id uuid default extensions.uuid_generate_v4() not null,
  name text not null,
  country_code text,
  external_id text,
  logo_url text,
  created_at timestamp with time zone default now() not null
);

create table public.tournament_predictions (
  id uuid default gen_random_uuid() not null,
  league_id uuid not null,
  user_id uuid not null,
  tournament_id uuid not null,
  winner_team text,
  runner_up_team text,
  third_place_team text,
  top_scorer text,
  points integer default 0 not null,
  locked boolean default false not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table public.tournament_results (
  id uuid default gen_random_uuid() not null,
  tournament_id uuid not null,
  winner_team text,
  runner_up_team text,
  third_place_team text,
  top_scorer text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table public.tournaments (
  id uuid default extensions.uuid_generate_v4() not null,
  name text not null,
  year integer not null,
  external_id text,
  created_at timestamp with time zone default now() not null
);

-- Primary keys, unique and check constraints
alter table public.audit_logs add constraint audit_logs_pkey PRIMARY KEY (id);
alter table public.companies add constraint companies_pkey PRIMARY KEY (id);
alter table public.company_members add constraint company_members_pkey PRIMARY KEY (id);
alter table public.company_members add constraint company_members_company_id_user_id_key UNIQUE (company_id, user_id);
alter table public.invitations add constraint invitations_pkey PRIMARY KEY (id);
alter table public.invitations add constraint invitations_invite_code_key UNIQUE (invite_code);
alter table public.league_members add constraint league_members_pkey PRIMARY KEY (id);
alter table public.league_members add constraint league_members_league_id_user_id_key UNIQUE (league_id, user_id);
alter table public.leagues add constraint leagues_pkey PRIMARY KEY (id);
alter table public.leagues add constraint leagues_invite_code_key UNIQUE (invite_code);
alter table public.matches add constraint matches_pkey PRIMARY KEY (id);
alter table public.matches add constraint matches_external_id_key UNIQUE (external_id);
alter table public.points add constraint points_pkey PRIMARY KEY (id);
alter table public.points add constraint points_league_id_user_id_match_id_key UNIQUE (league_id, user_id, match_id);
alter table public.predictions add constraint predictions_pkey PRIMARY KEY (id);
alter table public.predictions add constraint predictions_league_id_user_id_match_id_key UNIQUE (league_id, user_id, match_id);
alter table public.predictions add constraint predictions_predicted_away_goals_check CHECK ((predicted_away_goals >= 0));
alter table public.predictions add constraint predictions_predicted_home_goals_check CHECK ((predicted_home_goals >= 0));
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.teams add constraint teams_pkey PRIMARY KEY (id);
alter table public.tournament_predictions add constraint tournament_predictions_pkey PRIMARY KEY (id);
alter table public.tournament_predictions add constraint tournament_predictions_league_id_user_id_tournament_id_key UNIQUE (league_id, user_id, tournament_id);
alter table public.tournament_results add constraint tournament_results_pkey PRIMARY KEY (id);
alter table public.tournament_results add constraint tournament_results_tournament_id_key UNIQUE (tournament_id);
alter table public.tournaments add constraint tournaments_pkey PRIMARY KEY (id);

-- Foreign keys
alter table public.audit_logs add constraint audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.companies add constraint companies_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.company_members add constraint company_members_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_members add constraint company_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.invitations add constraint invitations_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.invitations add constraint invitations_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE;
alter table public.league_members add constraint league_members_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE;
alter table public.league_members add constraint league_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.leagues add constraint leagues_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.leagues add constraint leagues_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.leagues add constraint leagues_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE SET NULL;
alter table public.matches add constraint matches_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES teams(id);
alter table public.matches add constraint matches_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES teams(id);
alter table public.matches add constraint matches_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE;
alter table public.points add constraint points_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE;
alter table public.points add constraint points_match_id_fkey FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
alter table public.points add constraint points_prediction_id_fkey FOREIGN KEY (prediction_id) REFERENCES predictions(id) ON DELETE CASCADE;
alter table public.points add constraint points_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.predictions add constraint predictions_match_id_fkey FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
alter table public.predictions add constraint predictions_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE;
alter table public.predictions add constraint predictions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.tournament_predictions add constraint tournament_predictions_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE;
alter table public.tournament_predictions add constraint tournament_predictions_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE;
alter table public.tournament_predictions add constraint tournament_predictions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.tournament_results add constraint tournament_results_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX leagues_tournament_id_idx ON public.leagues USING btree (tournament_id);
CREATE INDEX points_league_id_idx ON public.points USING btree (league_id);
CREATE INDEX predictions_user_id_idx ON public.predictions USING btree (user_id);
CREATE INDEX points_match_id_idx ON public.points USING btree (match_id);
CREATE INDEX matches_kickoff_at_idx ON public.matches USING btree (kickoff_at);
CREATE INDEX matches_status_idx ON public.matches USING btree (status);
CREATE INDEX predictions_match_id_idx ON public.predictions USING btree (match_id);
CREATE INDEX matches_tournament_id_idx ON public.matches USING btree (tournament_id);
CREATE INDEX points_user_id_idx ON public.points USING btree (user_id);
CREATE INDEX predictions_league_id_idx ON public.predictions USING btree (league_id);

-- Functions
CREATE OR REPLACE FUNCTION public.calculate_prediction_points(prediction_id_input uuid)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  p record;
  m record;
  home_points int := 0;
  away_points int := 0;
  sign_points int := 0;
  total int := 0;
begin
  select * into p
  from public.predictions
  where id = prediction_id_input;

  if p.id is null then
    return 0;
  end if;

  select * into m
  from public.matches
  where id = p.match_id;

  if m.id is null or m.status <> 'finished' then
    return 0;
  end if;

  if p.predicted_home_goals = m.home_goals then
    home_points := 2;
  end if;

  if p.predicted_away_goals = m.away_goals then
    away_points := 2;
  end if;

  if public.match_sign(p.predicted_home_goals, p.predicted_away_goals) = public.match_sign(m.home_goals, m.away_goals) then
    sign_points := 3;
  end if;

  total := home_points + away_points + sign_points;

  insert into public.points (
    league_id,
    user_id,
    match_id,
    prediction_id,
    home_goal_points,
    away_goal_points,
    sign_points,
    total_points,
    calculated_at
  )
  values (
    p.league_id,
    p.user_id,
    p.match_id,
    p.id,
    home_points,
    away_points,
    sign_points,
    total,
    now()
  )
  on conflict (league_id, user_id, match_id)
  do update set
    home_goal_points = excluded.home_goal_points,
    away_goal_points = excluded.away_goal_points,
    sign_points = excluded.sign_points,
    total_points = excluded.total_points,
    calculated_at = now();

  return total;
end;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (
    id,
    full_name
  )
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'full_name',
      split_part(new.email, '@', 1)
    )
  );

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.join_league_by_code(invite_code_input text)
 RETURNS TABLE(league_id uuid, league_name text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_user_id uuid := auth.uid();
  v_league_id uuid;
  v_league_name text;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select l.id, l.name
    into v_league_id, v_league_name
  from leagues l
  where upper(l.invite_code) = upper(trim(invite_code_input))
  limit 1;

  -- No matching league: return zero rows; the caller treats this as "not found".
  if v_league_id is null then
    return;
  end if;

  if not exists (
    select 1 from league_members lm
    where lm.league_id = v_league_id
      and lm.user_id = v_user_id
  ) then
    insert into league_members (league_id, user_id, role)
    values (v_league_id, v_user_id, 'member');
  end if;

  return query select v_league_id, v_league_name;
end;
$function$;

CREATE OR REPLACE FUNCTION public.lock_predictions_for_started_matches()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  update public.predictions p
  set lock_status = 'locked', updated_at = now()
  from public.matches m
  where p.match_id = m.id
    and m.kickoff_at <= now()
    and p.lock_status = 'open';
end;
$function$;

CREATE OR REPLACE FUNCTION public.match_sign(home_goals integer, away_goals integer)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select case
    when home_goals = away_goals then 'X'
    when home_goals > away_goals then '1'
    else '2'
  end;
$function$;

CREATE OR REPLACE FUNCTION public.recalculate_points_after_match_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  if new.status = 'finished' then
    perform public.recalculate_points_for_match(new.id);
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.recalculate_points_for_match(match_id_input uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  prediction_record record;
begin
  for prediction_record in
    select id
    from public.predictions
    where match_id = match_id_input
  loop
    perform public.calculate_prediction_points(prediction_record.id);
  end loop;
end;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_leaderboard_for_league(league_id_input uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.leaderboard (
    league_id,
    user_id,
    full_name,
    total_points
  )
  select
    lm.league_id,
    lm.user_id,
    p.full_name,
    coalesce(sum(pt.total_points), 0)
  from public.league_members lm
  left join public.profiles p
    on p.id = lm.user_id
  left join public.points pt
    on pt.league_id = lm.league_id
    and pt.user_id = lm.user_id
  where lm.league_id = league_id_input
  group by lm.league_id, lm.user_id, p.full_name
  on conflict (league_id, user_id)
  do update set
    total_points = excluded.total_points,
    full_name = excluded.full_name;
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_match_result(match_id_input uuid, home_goals_input integer, away_goals_input integer)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  update public.matches
  set
    home_goals = home_goals_input,
    away_goals = away_goals_input,
    status = 'finished',
    updated_at = now()
  where id = match_id_input;

  perform public.recalculate_points_for_match(match_id_input);
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

-- Views
create or replace view public.leaderboard as
SELECT lm.league_id,
    lm.user_id,
    COALESCE(pr.full_name, 'Okänd spelare'::text) AS full_name,
    COALESCE(sum(pt.total_points), (0)::bigint) AS total_points
   FROM ((league_members lm
     LEFT JOIN profiles pr ON ((pr.id = lm.user_id)))
     LEFT JOIN points pt ON (((pt.league_id = lm.league_id) AND (pt.user_id = lm.user_id))))
  GROUP BY lm.league_id, lm.user_id, pr.full_name;

-- Triggers
CREATE TRIGGER set_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_companies_updated_at BEFORE UPDATE ON public.companies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_leagues_updated_at BEFORE UPDATE ON public.leagues FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_matches_updated_at BEFORE UPDATE ON public.matches FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_predictions_updated_at BEFORE UPDATE ON public.predictions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER recalculate_points_when_match_finished AFTER UPDATE OF status, home_goals, away_goals ON public.matches FOR EACH ROW EXECUTE FUNCTION recalculate_points_after_match_update();

-- Auth trigger: create a profile row whenever a new auth user signs up.
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- Row Level Security
alter table public.audit_logs enable row level security;
alter table public.companies enable row level security;
alter table public.company_members enable row level security;
alter table public.invitations enable row level security;
alter table public.league_members enable row level security;
alter table public.leagues enable row level security;
alter table public.matches enable row level security;
alter table public.points enable row level security;
alter table public.predictions enable row level security;
alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.tournament_predictions enable row level security;
alter table public.tournament_results enable row level security;
alter table public.tournaments enable row level security;

-- Policies
create policy "League owners can insert members" on public.league_members
  as permissive
  for insert
  to public
  with check ((EXISTS ( SELECT 1
   FROM leagues l
  WHERE ((l.id = league_members.league_id) AND (l.owner_id = auth.uid())))));

create policy "Users can insert own league membership" on public.league_members
  as permissive
  for insert
  to public
  with check ((user_id = auth.uid()));

create policy "Users can read own league memberships" on public.league_members
  as permissive
  for select
  to public
  using ((user_id = auth.uid()));

create policy "Authenticated users can create leagues" on public.leagues
  as permissive
  for insert
  to authenticated
  with check ((auth.uid() = owner_id));

create policy "League admins can update leagues" on public.leagues
  as permissive
  for update
  to public
  using ((EXISTS ( SELECT 1
   FROM league_members lm
  WHERE ((lm.league_id = leagues.id) AND (lm.user_id = auth.uid()) AND (lm.role = 'admin'::league_member_role)))));

create policy "Users can read leagues by membership" on public.leagues
  as permissive
  for select
  to authenticated
  using ((id IN ( SELECT league_members.league_id
   FROM league_members
  WHERE (league_members.user_id = auth.uid()))));

create policy "Users can read owned leagues" on public.leagues
  as permissive
  for select
  to authenticated
  using ((owner_id = auth.uid()));

create policy "Admin can update matches" on public.matches
  as permissive
  for update
  to authenticated
  using ((lower((auth.jwt() ->> 'email'::text)) = 'rabimasso@hotmail.com'::text))
  with check ((lower((auth.jwt() ->> 'email'::text)) = 'rabimasso@hotmail.com'::text));

create policy "Authenticated users can read matches" on public.matches
  as permissive
  for select
  to authenticated
  using (true);

create policy "Users can read points in their leagues" on public.points
  as permissive
  for select
  to public
  using ((EXISTS ( SELECT 1
   FROM league_members lm
  WHERE ((lm.league_id = points.league_id) AND (lm.user_id = auth.uid())))));

create policy "Users can insert their own predictions" on public.predictions
  as permissive
  for insert
  to public
  with check (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM league_members lm
  WHERE ((lm.league_id = predictions.league_id) AND (lm.user_id = auth.uid())))) AND (EXISTS ( SELECT 1
   FROM matches m
  WHERE ((m.id = predictions.match_id) AND (m.kickoff_at > now()))))));

create policy "Users can read predictions in their leagues" on public.predictions
  as permissive
  for select
  to public
  using ((EXISTS ( SELECT 1
   FROM league_members lm
  WHERE ((lm.league_id = predictions.league_id) AND (lm.user_id = auth.uid())))));

create policy "Users can update their own unlocked predictions" on public.predictions
  as permissive
  for update
  to public
  using (((auth.uid() = user_id) AND (lock_status = 'open'::prediction_lock_status) AND (EXISTS ( SELECT 1
   FROM matches m
  WHERE ((m.id = predictions.match_id) AND (m.kickoff_at > now()))))));

create policy "Users can insert own profile" on public.profiles
  as permissive
  for insert
  to authenticated
  with check ((auth.uid() = id));

create policy "Users can read their own profile" on public.profiles
  as permissive
  for select
  to public
  using ((auth.uid() = id));

create policy "Users can update their own profile" on public.profiles
  as permissive
  for update
  to public
  using ((auth.uid() = id));

create policy "Authenticated users can read teams" on public.teams
  as permissive
  for select
  to authenticated
  using (true);

create policy "Users can create own tournament predictions" on public.tournament_predictions
  as permissive
  for insert
  to authenticated
  with check ((user_id = auth.uid()));

create policy "Users can insert their own tournament predictions" on public.tournament_predictions
  as permissive
  for insert
  to authenticated
  with check ((auth.uid() = user_id));

create policy "Users can read tournament predictions" on public.tournament_predictions
  as permissive
  for select
  to authenticated
  using (true);

create policy "Users can read tournament predictions in their leagues" on public.tournament_predictions
  as permissive
  for select
  to authenticated
  using (((user_id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM league_members lm
  WHERE ((lm.league_id = tournament_predictions.league_id) AND (lm.user_id = auth.uid()))))));

create policy "Users can update own unlocked tournament predictions" on public.tournament_predictions
  as permissive
  for update
  to authenticated
  using (((user_id = auth.uid()) AND (locked = false)))
  with check (((user_id = auth.uid()) AND (locked = false)));

create policy "Users can update their own tournament predictions" on public.tournament_predictions
  as permissive
  for update
  to authenticated
  using ((auth.uid() = user_id));

create policy "Authenticated users can read tournaments" on public.tournaments
  as permissive
  for select
  to authenticated
  using (true);

-- Grants (PostgREST roles)
grant delete, insert, references, select, trigger, truncate, update on public.audit_logs to anon;
grant delete, insert, references, select, trigger, truncate, update on public.audit_logs to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.audit_logs to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.companies to anon;
grant delete, insert, references, select, trigger, truncate, update on public.companies to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.companies to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.company_members to anon;
grant delete, insert, references, select, trigger, truncate, update on public.company_members to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.company_members to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.invitations to anon;
grant delete, insert, references, select, trigger, truncate, update on public.invitations to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.invitations to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.leaderboard to anon;
grant delete, insert, references, select, trigger, truncate, update on public.leaderboard to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.leaderboard to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.league_members to anon;
grant delete, insert, references, select, trigger, truncate, update on public.league_members to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.league_members to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.leagues to anon;
grant delete, insert, references, select, trigger, truncate, update on public.leagues to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.leagues to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.matches to anon;
grant delete, insert, references, select, trigger, truncate, update on public.matches to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.matches to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.points to anon;
grant delete, insert, references, select, trigger, truncate, update on public.points to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.points to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.predictions to anon;
grant delete, insert, references, select, trigger, truncate, update on public.predictions to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.predictions to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.profiles to anon;
grant delete, insert, references, select, trigger, truncate, update on public.profiles to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.profiles to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.teams to anon;
grant delete, insert, references, select, trigger, truncate, update on public.teams to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.teams to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.tournament_predictions to anon;
grant delete, insert, references, select, trigger, truncate, update on public.tournament_predictions to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.tournament_predictions to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.tournament_results to anon;
grant delete, insert, references, select, trigger, truncate, update on public.tournament_results to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.tournament_results to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.tournaments to anon;
grant delete, insert, references, select, trigger, truncate, update on public.tournaments to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.tournaments to service_role;
